

/*View structure for view bet_user */

/*!50001 DROP TABLE IF EXISTS `bet_user` */;
/*!50001 CREATE ALGORITHM=UNDEFINED  SQL SECURITY DEFINER VIEW `bet_user` AS select `k_bet`.`bid` AS `bid`,`k_bet`.`ball_sort` AS `ball_sort`,`k_bet`.`point_column` AS `point_column`,`k_bet`.`match_name` AS `match_name`,`k_bet`.`master_guest` AS `master_guest`,`k_bet`.`match_id` AS `match_id`,`k_bet`.`bet_info` AS `bet_info`,`k_bet`.`match_showtype` AS `match_showtype`,`k_bet`.`match_rgg` AS `match_rgg`,`k_bet`.`match_dxgg` AS `match_dxgg`,`k_bet`.`match_nowscore` AS `match_nowscore`,`k_bet`.`match_type` AS `match_type`,`k_bet`.`bet_money` AS `bet_money`,`k_bet`.`ben_add` AS `ben_add`,`k_bet`.`bet_point` AS `bet_point`,`k_bet`.`bet_win` AS `bet_win`,`k_bet`.`win` AS `win`,`k_bet`.`bet_time` AS `bet_time`,`k_bet`.`match_time` AS `match_time`,`k_bet`.`match_endtime` AS `match_endtime`,`k_bet`.`status` AS `status`,`k_bet`.`lose_ok` AS `lose_ok`,`k_bet`.`update_time` AS `update_time`,`k_bet`.`sys_about` AS `sys_about`,`k_bet`.`MB_Inball` AS `MB_Inball`,`k_bet`.`TG_Inball` AS `TG_Inball`,`k_bet`.`number` AS `number`,`k_bet`.`is_jiesuan` AS `is_jiesuan`,`k_bet`.`balance` AS `balance`,`k_bet`.`Match_HRedCard` AS `Match_HRedCard`,`k_bet`.`Match_GRedCard` AS `Match_GRedCard`,`k_bet`.`assets` AS `assets`,`k_bet`.`www` AS `www`,`k_bet`.`match_coverdate` AS `match_coverdate`,`k_bet`.`fs` AS `fs`,`k_bet`.`check` AS `check`,`k_bet`.`q_qian` AS `q_qian`,`k_bet`.`h_qian` AS `h_qian`,`k_bet`.`master` AS `master`,`k_bet`.`guest` AS `guest`,`k_bet`.`saltCode` AS `saltCode`,`k_bet`.`commission` AS `commission`,`k_bet`.`commissioned` AS `commissioned`,`k_bet`.`istongji` AS `istongji`,`k_bet`.`uid` AS `uid`,`k_user`.`username` AS `username` from (`k_bet` join `k_user` on((`k_bet`.`uid` = `k_user`.`uid`))) */;

/*View structure for view bet_user_copy */

/*!50001 DROP TABLE IF EXISTS `bet_user_copy` */;
/*!50001 CREATE ALGORITHM=UNDEFINED  SQL SECURITY DEFINER VIEW `bet_user_copy` AS select `k_bet`.`bid` AS `bid`,`k_bet`.`ball_sort` AS `ball_sort`,`k_bet`.`point_column` AS `point_column`,`k_bet`.`match_name` AS `match_name`,`k_bet`.`master_guest` AS `master_guest`,`k_bet`.`match_id` AS `match_id`,`k_bet`.`bet_info` AS `bet_info`,`k_bet`.`match_showtype` AS `match_showtype`,`k_bet`.`match_rgg` AS `match_rgg`,`k_bet`.`match_dxgg` AS `match_dxgg`,`k_bet`.`match_nowscore` AS `match_nowscore`,`k_bet`.`match_type` AS `match_type`,`k_bet`.`bet_money` AS `bet_money`,`k_bet`.`ben_add` AS `ben_add`,`k_bet`.`bet_point` AS `bet_point`,`k_bet`.`bet_win` AS `bet_win`,`k_bet`.`win` AS `win`,`k_bet`.`bet_time` AS `bet_time`,`k_bet`.`match_time` AS `match_time`,`k_bet`.`match_endtime` AS `match_endtime`,`k_bet`.`status` AS `status`,`k_bet`.`lose_ok` AS `lose_ok`,`k_bet`.`update_time` AS `update_time`,`k_bet`.`sys_about` AS `sys_about`,`k_bet`.`MB_Inball` AS `MB_Inball`,`k_bet`.`TG_Inball` AS `TG_Inball`,`k_bet`.`number` AS `number`,`k_bet`.`is_jiesuan` AS `is_jiesuan`,`k_bet`.`balance` AS `balance`,`k_bet`.`Match_HRedCard` AS `Match_HRedCard`,`k_bet`.`Match_GRedCard` AS `Match_GRedCard`,`k_bet`.`assets` AS `assets`,`k_bet`.`www` AS `www`,`k_bet`.`match_coverdate` AS `match_coverdate`,`k_bet`.`fs` AS `fs`,`k_bet`.`check` AS `check`,`k_bet`.`q_qian` AS `q_qian`,`k_bet`.`h_qian` AS `h_qian`,`k_bet`.`master` AS `master`,`k_bet`.`guest` AS `guest`,`k_bet`.`saltCode` AS `saltCode`,`k_bet`.`commission` AS `commission`,`k_bet`.`commissioned` AS `commissioned`,`k_bet`.`istongji` AS `istongji`,`k_bet`.`uid` AS `uid`,`k_user`.`username` AS `username` from (`k_bet` join `k_user` on((`k_bet`.`uid` = `k_user`.`uid`))) */;

/*View structure for view cglist */

/*!50001 DROP TABLE IF EXISTS `cglist` */;
/*!50001 CREATE ALGORITHM=UNDEFINED  SQL SECURITY DEFINER VIEW `cglist` AS select `k_bet_cg_group`.`gid` AS `gid`,`k_bet_cg_group`.`bet_time` AS `gbet_time`,`k_bet_cg_group`.`bet_money` AS `bet_money`,`k_bet_cg_group`.`cg_count` AS `cg_count`,`k_bet_cg_group`.`bet_win` AS `bet_win`,`k_bet_cg_group`.`win` AS `win`,`k_bet_cg`.`bid` AS `bid`,`k_bet_cg`.`bet_time` AS `bet_time`,`k_bet_cg`.`bet_info` AS `bet_info`,`k_bet_cg`.`match_name` AS `match_name`,`k_bet_cg`.`master_guest` AS `master_guest`,`k_bet_cg`.`MB_Inball` AS `MB_Inball`,`k_bet_cg`.`TG_Inball` AS `TG_Inball`,`k_bet_cg_group`.`uid` AS `uid`,`k_bet_cg_group`.`fs` AS `fs`,`k_bet_cg`.`match_dxgg` AS `match_dxgg`,`k_bet_cg`.`match_rgg` AS `match_rgg`,`k_bet_cg`.`match_showtype` AS `match_showtype`,`k_bet_cg`.`point_column` AS `point_column`,`k_bet_cg`.`ball_sort` AS `ball_sort`,`k_bet_cg`.`bet_point` AS `bet_point`,`k_bet_cg`.`master` AS `master`,`k_bet_cg`.`guest` AS `guest`,`k_bet_cg_group`.`status` AS `status`,`k_bet_cg`.`status` AS `match_status` from (`k_bet_cg` join `k_bet_cg_group` on((`k_bet_cg`.`gid` = `k_bet_cg_group`.`gid`))) where (`k_bet_cg_group`.`status` in (0,2)) */;

/*View structure for view daili */

/*!50001 DROP TABLE IF EXISTS `daili` */;
/*!50001 CREATE ALGORITHM=UNDEFINED  SQL SECURITY DEFINER VIEW `daili` AS select `k_user_daili`.`d_id` AS `d_id`,`k_user_daili`.`uid` AS `uid`,`k_user_daili`.`r_name` AS `r_name`,`k_user_daili`.`mobile` AS `mobile`,`k_user_daili`.`email` AS `email`,`k_user_daili`.`msn_qq` AS `msn_qq`,`k_user_daili`.`about` AS `about`,`k_user_daili`.`status` AS `status`,`k_user_daili`.`add_time` AS `add_time`,`k_user`.`username` AS `username` from (`k_user_daili` left join `k_user` on((`k_user_daili`.`uid` = `k_user`.`uid`))) order by `k_user_daili`.`d_id` desc */;

/*View structure for view g_user_login */

/*!50001 DROP TABLE IF EXISTS `g_user_login` */;
/*!50001 CREATE ALGORITHM=UNDEFINED  SQL SECURITY DEFINER VIEW `g_user_login` AS select `a`.`uid` AS `uid`,`a`.`username` AS `username`,`a`.`money` AS `money`,`a`.`reg_ip` AS `reg_ip`,`a`.`login_ip` AS `login_ip`,`a`.`is_daili` AS `is_daili`,`a`.`is_stop` AS `is_stop`,`a`.`pay_name` AS `pay_name`,`a`.`mobile` AS `mobile`,`a`.`qq` AS `qq`,`a`.`reg_date` AS `reg_date`,`a`.`login_time` AS `login_time`,`k_user_login`.`www` AS `www`,`k_group`.`name` AS `name`,`b`.`username` AS `topuser`,`k_user_login`.`is_login` AS `ul_type` from (((`k_user` `a` left join `k_user` `b` on((`a`.`top_uid` = `b`.`uid`))) left join `k_user_login` on((`k_user_login`.`uid` = `a`.`uid`))) left join `k_group` on((`k_group`.`id` = `a`.`gid`))) */;

/*View structure for view havebet_bk */

/*!50001 DROP TABLE IF EXISTS `havebet_bk` */;
/*!50001 CREATE ALGORITHM=UNDEFINED  SQL SECURITY DEFINER VIEW `havebet_bk` AS select distinct `test_188sport1_db`.`lq_match`.`Match_Time` AS `Match_Time`,`test_188sport1_db`.`lq_match`.`Match_Master` AS `Match_Master`,`test_188sport1_db`.`lq_match`.`Match_Guest` AS `Match_Guest`,`test_188sport1_db`.`lq_match`.`Match_Name` AS `Match_Name`,`test_188sport1_db`.`lq_match`.`MB_Inball_1st` AS `MB_Inball_1st`,`test_188sport1_db`.`lq_match`.`MB_Inball_2st` AS `MB_Inball_2st`,`test_188sport1_db`.`lq_match`.`MB_Inball_3st` AS `MB_Inball_3st`,`test_188sport1_db`.`lq_match`.`MB_Inball_4st` AS `MB_Inball_4st`,`test_188sport1_db`.`lq_match`.`MB_Inball_Add` AS `MB_Inball_Add`,`test_188sport1_db`.`lq_match`.`TG_Inball_1st` AS `TG_Inball_1st`,`test_188sport1_db`.`lq_match`.`TG_Inball_2st` AS `TG_Inball_2st`,`test_188sport1_db`.`lq_match`.`TG_Inball_3st` AS `TG_Inball_3st`,`test_188sport1_db`.`lq_match`.`TG_Inball_4st` AS `TG_Inball_4st`,`test_188sport1_db`.`lq_match`.`TG_Inball_Add` AS `TG_Inball_Add`,`test_188sport1_db`.`lq_match`.`MB_Inball` AS `MB_Inball`,`test_188sport1_db`.`lq_match`.`TG_Inball` AS `TG_Inball`,`test_188sport1_db`.`lq_match`.`MB_Inball_HR` AS `MB_Inball_HR`,`test_188sport1_db`.`lq_match`.`TG_Inball_HR` AS `TG_Inball_HR`,`test_188sport1_db`.`lq_match`.`MB_Inball_ER` AS `MB_Inball_ER`,`test_188sport1_db`.`lq_match`.`TG_Inball_ER` AS `TG_Inball_ER`,`test_188sport1_db`.`lq_match`.`MB_Inball_OK` AS `MB_Inball_OK`,`test_188sport1_db`.`lq_match`.`TG_Inball_OK` AS `TG_Inball_OK`,`test_188sport1_db`.`lq_match`.`Match_Date` AS `Match_Date`,`test_188sport1_db`.`lq_match`.`Match_JS` AS `Match_JS`,`test_188sport1_db`.`lq_match`.`Match_ID` AS `Match_ID` from (`test_188ksb1_db`.`k_bet` join `test_188sport1_db`.`lq_match` on(((`test_188ksb1_db`.`k_bet`.`match_id` = `test_188sport1_db`.`lq_match`.`Match_ID`) and (`test_188sport1_db`.`lq_match`.`Match_ID` = `test_188ksb1_db`.`k_bet`.`match_id`)))) order by `test_188sport1_db`.`lq_match`.`Match_CoverDate` desc,`test_188sport1_db`.`lq_match`.`iPage` desc,`test_188sport1_db`.`lq_match`.`Match_Name` desc,`test_188sport1_db`.`lq_match`.`Match_Master` desc,`test_188sport1_db`.`lq_match`.`iSn` desc */;

/*View structure for view havebet_ft */

/*!50001 DROP TABLE IF EXISTS `havebet_ft` */;
/*!50001 CREATE ALGORITHM=UNDEFINED  SQL SECURITY DEFINER VIEW `havebet_ft` AS select `test_188sport1_db`.`bet_match`.`Match_ID` AS `Match_ID`,`test_188sport1_db`.`bet_match`.`Match_Date` AS `Match_Date`,`test_188sport1_db`.`bet_match`.`Match_Time` AS `Match_Time`,`test_188sport1_db`.`bet_match`.`Match_Master` AS `Match_Master`,`test_188sport1_db`.`bet_match`.`Match_Name` AS `Match_Name`,`test_188sport1_db`.`bet_match`.`Match_Guest` AS `Match_Guest`,`test_188sport1_db`.`bet_match`.`MB_Inball` AS `MB_Inball`,`test_188sport1_db`.`bet_match`.`TG_Inball` AS `TG_Inball`,`test_188sport1_db`.`bet_match`.`MB_Inball_HR` AS `MB_Inball_HR`,`test_188sport1_db`.`bet_match`.`TG_Inball_HR` AS `TG_Inball_HR`,`test_188sport1_db`.`bet_match`.`Match_SBJS` AS `Match_SBJS`,`test_188sport1_db`.`bet_match`.`Match_JS` AS `Match_JS` from (`test_188sport1_db`.`bet_match` join `test_188ksb1_db`.`k_bet` on((`test_188sport1_db`.`bet_match`.`Match_ID` = `test_188ksb1_db`.`k_bet`.`match_id`))) order by `test_188sport1_db`.`bet_match`.`Match_CoverDate` desc,`test_188sport1_db`.`bet_match`.`Match_Name` desc,`test_188sport1_db`.`bet_match`.`Match_Master` desc */;

/*View structure for view huikuan_user */

/*!50001 DROP TABLE IF EXISTS `huikuan_user` */;
/*!50001 CREATE ALGORITHM=UNDEFINED  SQL SECURITY DEFINER VIEW `huikuan_user` AS select `huikuan`.`id` AS `id`,`huikuan`.`money` AS `money`,`huikuan`.`bank` AS `bank`,`huikuan`.`date` AS `date`,`huikuan`.`manner` AS `manner`,`huikuan`.`address` AS `address`,`huikuan`.`status` AS `status`,`huikuan`.`uid` AS `uid`,`huikuan`.`lsh` AS `lsh`,`huikuan`.`zsjr` AS `zsjr`,`huikuan`.`assets` AS `assets`,`huikuan`.`balance` AS `balance`,`huikuan`.`adddate` AS `adddate`,`huikuan`.`q_qian` AS `q_qian`,`huikuan`.`h_qian` AS `h_qian`,`k_user`.`username` AS `username`,`k_user`.`gid` AS `gid` from (`huikuan` join `k_user` on((`huikuan`.`uid` = `k_user`.`uid`))) */;
